### ISSUE TITLE
EFI partition requirement unnecessarily enforced on all devices

### ISSUE THREAD

**Issue by jonaslb** [rhinstaller/anaconda#1128]
I am just installing fedora 26 right now. I have multiple hard drives that I only use for data. I wanted to set one of them to a fixed mount point during installation (using the "advanced custom" interface). 

When choosing devices for installation, I chose the two devices (hdd and ssd). I was then sent to the partition/formatting/mount point screen, and set a mount point for the hdd and configured the ssd for installation including an efi partition.

Anaconda complained that I had not set an EFI partition, even though it was correctly set up on the ssd.

When only choosing the ssd for installation, but configuring it the same way, anaconda will let the installation continue just fine. 

I was thus forced to continue without setting a mount point for my extra hard drive. But Anaconda should probably only enforce one efi partition in total. Either that or it might be an ordering issue - the hdd was listed above the ssd in the list (in which case the title of this issue would be slightly inaccurate).

**Comment by da2x** [comment]
There are really three issues here:

1. The error message incorrectly says you don’t have the required EFI partition even though you do. This is confusing.
2. Anaconda requires you to have /boot and /boot/efi on the same physical drive. If you don’t then you get the above confusing (and wrong) error message. This isn’t a requirement of either grub2 or the UEFI spec.
3. Boot loader selection on storage screen 1 should be moved to screen 2. Or at least there should be an indicator on screen 2 showing where it is and inform you to go back to to screen 1 to change it.

**Comment by jkonecny12** [comment]
Hello, please file this bug to the redhat bugzilla. We are not focusing on issues filed here. It is harder to work here on issues with other components in the system.

**Comment by da2x** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1589332
