### ISSUE TITLE
nokill (and maybe other important options) are missing from the boot options documentation

### ISSUE THREAD

**Issue by kparal** [rhinstaller/anaconda#113]
Today, anaconda hard rebooted for me in the middle of the installation:
https://bugzilla.redhat.com/show_bug.cgi?id=1224048

I vaguely remembered that it is intentional in certain cases and there is some way to make it stop doing that, but I couldn't find any documentation about it. https://fedoraproject.org/wiki/Anaconda_Boot_Options is now empty and it leads to https://rhinstaller.github.io/anaconda/boot-options.html which seems to be generated from https://github.com/rhinstaller/anaconda/blob/master/docs/boot-options.rst . But there was nothing in the section I'd expect this to be:
https://rhinstaller.github.io/anaconda/boot-options.html#debugging-and-troubleshooting

Finally I thought of looking at the historic option of the wiki page, and there it was, `nokill`!
https://fedoraproject.org/w/index.php?title=Anaconda_Boot_Options&oldid=403507

Please make sure all the important options are in the new documentation, or leave the old one around until the new one is up-to-date. Thank you!

**Comment by bcl** [comment]
These need to be reconciled with the current code on master, for example inst.nogpt doesn't exist anymore, that was a leftover from F17 (IIRC) where we tried to make GPT disklabels by default.

**Comment by vpodzime** [comment]
> These need to be reconciled with the current code on master, for example inst.nogpt doesn't exist anymore, that was a leftover from F17 (IIRC) where we tried to make GPT disklabels by default.

That should be changed to ``inst.gpt`` which we still check at least according to the *pyanaconda/flags.py*.

> Also, I don't think we should start referencing pull numbers in our commit messages, that should be reserved for bugzilla. It may be ok to mention them in the body of the commit message though. Maybe we should adopt something like ghpull: #113

Agreed, but I'm for just ``gh:#113`` as these are issues not pull requests and the number is just incremented for every new issue/PR anyway (there is never an issue with the same number as some PR).

**Comment by vpodzime** [comment]
Resolved.
