### ISSUE TITLE
dnf.exceptions.ConfigError: Repository New_Repository has no mirror or baseurl set.

### ISSUE THREAD

**Issue by skoam** [rhinstaller/anaconda#114]
When adding a new repository and leaving the configuration panel without providing a base_url, an unknown error is thrown. I uploaded the report here:

http://www.fumiko-game.com/files/report.tar.gz

*What did I do?*

- Went to repository configuration
- Clicked on "Add a repository"
- Left the panel without providing anything
- Unknown error is thrown, "Quit" rebooted the system

*What should happen?*

- An error message should be shown that "base url is empty"
- Invalid repositories could just be kicked out from the configuration

**Comment by bcl** [comment]
Please report this via bugzilla at https://bugzilla.redhat.com/enter_bug.cgi?component=anaconda&product=Fedora and attach the logs as individual text/plain attachments.
