### ISSUE TITLE
Disk partition doesn't allow 4 primary partitions on MSDOS disk layout

### ISSUE THREAD

**Issue by nullr0ute** [rhinstaller/anaconda#1205]
4 primary partitions is a completely valid configuration for a disk layout, and while it won't allow for creation of further partitions it's still a correct and completely valid usecase.

We use an explicit 4 primary partitions for ARM SBCs which works fine with the old appliance-tools but doesn't with anaconda.

This configuration fails in the kickstart:
<pre>
zerombr
clearpart --all --initlabel --disklabel=msdos
part /boot/fw --size=50 --fstype vfat --asprimary
part /boot --size=512 --fstype ext4 --asprimary --active
part swap --size=512 --fstype swap --asprimary
part / --size=2900 --fstype ext4 --asprimary
</pre>

This is causing us problems (and complaints) for aarch64 SBC images in F-27 because people are expecting the same as the ARMv7 ones and they're not

**Comment by jkonecny12** [comment]
Hello,
Please file a bug in [Bugzilla](https://bugzilla.redhat.com/).

We need it there to be able to change components and track it.

I'm closing this issue here.

**Comment by nullr0ute** [comment]
I wish this team would have a consistent means of dealing with this, I get told to do both

**Comment by nullr0ute** [comment]
I wish this team would have a consistent means of dealing with this, I get told to do both

https://bugzilla.redhat.com/show_bug.cgi?id=1498527

**Comment by jkonecny12** [comment]
I don't know who told you to create an issue in GitHub, however, AFAIK bugzilla is always preferred in our team.
