### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by cadeon** [rhinstaller/anaconda#147]
Change the window title of all fatal errors to "My anaconda don't"

**Comment by M4rtinK** [comment]
I don't understand what is being requested here so I'm closing this. Feel free to reopen if you can provide more information.

**Comment by mpeter88** [comment]
Reference: www.youtube.com/watch?v=LDZX4ooRsWs

**Comment by wgwoods** [comment]
not sure we can implement this without the permission of upstream maintainers, but if you can get smixalot or nminaj to send a PR we'll definitely reconsider.
