### ISSUE TITLE
Consider adding more system-reserved user names

### ISSUE THREAD

**Issue by ykgmfq** [rhinstaller/anaconda#1501]
Currently, the list of system-reserved user names is quite short:
```python
# Check reserved names.
if name in os.listdir("/") + ["root", "home", "daemon", "system"]:
    return False, _("User name is reserved for system: %s") % name
````
However, these are the users I have on Fedora Workstation:
```
$ cut -d: -f1 /etc/passwd
root
bin
daemon
adm
lp
sync
shutdown
halt
mail
operator
games
ftp
nobody
apache
systemd-coredump
systemd-timesync
systemd-network
systemd-resolve
dbus
polkitd
geoclue
colord
rtkit
pulse
abrt
gluster
qemu
pipewire
nm-openconnect
avahi
usbmuxd
rpc
saslauth
openvpn
nm-openvpn
radvd
setroubleshoot
gdm
rpcuser
gnome-initial-setup
sshd
chrony
tss
tcpdump
mysql
unbound
akmods
dnsmasq
```
I once tried to create a user for someone whose initials are "lp", which failed. In my opinion all of these should be included in the check.

**Comment by jkonecny12** [comment]
Can you please file a bug in bugzilla.redhat.com for this. Thank you.

**Comment by ykgmfq** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1589064

**Comment by jkonecny12** [comment]
It is tracked on bugzilla now. Closing this issue. Thanks.
