### ISSUE TITLE
Create an install class for the atomic workstation

### ISSUE THREAD

**Issue by matthiasclasen** [rhinstaller/anaconda#1505]
... or Silverblue, as it is called now. The install class should probably inherit from the workstation, since we don't really want to make any changes right now.

This came up in: https://pagure.io/teamsilverblue/issue/20

**Comment by jkonecny12** [comment]
PR: https://github.com/rhinstaller/anaconda/pull/1510

**Comment by jkonecny12** [comment]
@matthiasclasen 
Is the "Silverblue" name as product variant correct?
Do you want to have your own branding on this point? If you do I need to change path to this stylesheet css file.

**Comment by matthiasclasen** [comment]
I don't know what it means for a product variant name to be correct.
But if I have to make a guess: yes, looks like the name i want

**Comment by jkonecny12** [comment]
@matthiasclasen that needs to be set properly in lorax when the compose is created. Anaconda will match install class based on the Lorax build parameters.

**Comment by jkonecny12** [comment]
PR mentioned above is merged. Closing this issue.

**Comment by matthiasclasen** [comment]
thank you
