### ISSUE TITLE
Unable to create process using

### ISSUE THREAD

**Issue by spajai** [rhinstaller/anaconda#1596]
PS C:\Anaconda3\pkgs\anaconda-navigator-1.8.7-py36_0\Scripts> .\anaconda-navigator.exe
Unable to create process using 'C:\Anaconda3\pkgs\anaconda-navigator-1.8.7-py36_0\python.exe C:\Anaconda3\pkgs\anaconda-navigator-1.8.7-py36_0\Scripts\anaconda-navigator-script.py '

**Comment by poncovka** [comment]
Hi, please report your issue to the right project. This Anaconda is an installer for Fedora and RHEL :-)
