### ISSUE TITLE
Create an install class for Fedora Workstation

### ISSUE THREAD

**Issue by stickster** [rhinstaller/anaconda#1600]
We'd like to be able to pass `inst.instclass="Fedora Workstation"` and have it select the proper product defaults, so we can get rid of the separate Workstation installation tree. See also https://pagure.io/fedora-workstation/issue/45 and https://pagure.io/releng/issue/7403 for background.

**Comment by jkonecny12** [comment]
We are thinking about change of install class quite a bit and maybe replace them completely. So we definitely want to use something different than instclass. This is our proposal how it may work.

* Add `inst.product` and `inst.variant`. This would work as override for buildstamp values which are created when the image is build (Lorax). Right now the install class is matching against these values.

**Comment by jkonecny12** [comment]
Also for which Fedora version is this targeted?

**Comment by dustymabe** [comment]
> Also for which Fedora version is this targeted?

probably fedora 30, changing f29 compose process at this point would be risky IMHO

**Comment by poncovka** [comment]
Btw. options `inst.product` and `inst.variant` could be also interesting for live installations. They could replace the hack for variants that we have in the `liveinst` script. See: https://github.com/rhinstaller/anaconda/commit/3eccbf2

**Comment by dustymabe** [comment]
Could we make progress on this so we can have it for F30?

**Comment by poncovka** [comment]
It is planned for the next week or so.

**Comment by poncovka** [comment]
Implemented at: https://github.com/rhinstaller/anaconda/pull/1716

**Comment by poncovka** [comment]
Released in `anaconda-30.15-1`. See the [documentation](https://github.com/rhinstaller/anaconda/blob/master/docs/boot-options.rst#product-options).
