### ISSUE TITLE
Odd name resolution problems

### ISSUE THREAD

**Issue by jasontibbitts** [rhinstaller/anaconda#163]
This is probably very specific to my setup and there's a quite trivial workaround but I might as well file this just in case there's an easy fix.

I generally install by booting the PXE images off of a USB stick, and specifying the URL of a kickstart file on the command line.  Dracut does DHCP and downloads the kickstart and *.img files.  The kickstart file has a network line specifying a static network configuration, so anaconda changes the net config and makes a VNC connection.  This all works great.

The problem is this: anaconda will fail to set up the repositories properly if, in the repository definitions, I use an unqualified hostname.  If I use the IP of the server (which breaks virtual hosting) or the FQDN then everything's OK.  Or, if I just click on the error and then click 'done' everything is fine.  If I ssh in I can resolve hostnames just fine.  There's only a short window when it appears not to be able to resolve hostnames.

I suspect some sort of race with networkmanager; in my experience it can take a little while to actually write out resolv.conf.  I could drop in a sleep somewhere but I'm having trouble figuring out exactly where in the source to do that.

**Comment by dashea** [comment]
This sounds like a NetworkManager problem. anaconda waits for NetworkManager to report a state of (usually) CONNECTED_GLOBAL, and it ought to be done writing /etc/resolv.conf if it's reporting that it's connected. Adding sleeps in anaconda to work around that just sounds like trouble.

**Comment by jasontibbitts** [comment]
Yes, NetworkManager should be the guilty party here.  I was hoping for a clue as to where I might add a sleep to work around this locally since fixing NetworkManager is a bit more difficult than tweaking Anaconda.  Saying it's someone else's problem doesn't actually get things working so sometimes a quick hack in an updates.img is simply what you need to get the job done.  I'll figure it out on myself.
