### ISSUE TITLE
Make rpmostree payload progress messages translatable

### ISSUE THREAD

**Issue by AsciiWolf** [rhinstaller/anaconda#1630]
The progress messages (_progressQ.send_message_) of the rpmostree payload (_pyanaconda/payload/rpmostreepayload.py_) are currently not translatable on Zanata. Please, consider marking them for translation.

**Comment by jkonecny12** [comment]
PR: https://github.com/rhinstaller/anaconda/pull/1631

**Comment by Jibec** [comment]
isn't this to be closed?

**Comment by jkonecny12** [comment]
Closed by https://github.com/rhinstaller/anaconda/pull/1631

**Comment by jkonecny12** [comment]
Thanks for pointing this out @Jibec
