### ISSUE TITLE
Anaconda cannot assemble  Intel RSTE/VROC RAID when installing RHEL7.5

### ISSUE THREAD

**Issue by yuzaipiaofei** [rhinstaller/anaconda#1678]
Anaconda cannot assemble Intel RSTE/VROC RAID when installing RHEL7.5.
If i run the mdadm --assemble --scan or mdadm -As
The virtual raid device will be created 
#/dev/md126p1 
#/dev/md126p2
#/dev/md126p3

**Comment by jkonecny12** [comment]
Please file this on the https://bugzilla.redhat.com . We are not able to help you without the bug there.
