### ISSUE TITLE
Question: treeinfo checksums requirements?

### ISSUE THREAD

**Issue by lubomir** [rhinstaller/anaconda#1687]
When anaconda reads the `.treeinfo` file, does it somehow care about the image checksums in there?

I did not find any mention in the code, but I'd rather ask to be sure.

Would you care if the checksum algorithm was changed? Right now there's SHA256, and we have [a request to use SHA512](https://pagure.io/pungi/issue/591).

**Comment by jkonecny12** [comment]
Hi Lubomir,
AFAICT, no we are not comparing checksums. I think we should do that (or maybe dracut is better component) but right now we are not.

**Comment by lubomir** [comment]
Thank you very much!
