### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by 102464** [rhinstaller/anaconda#1822]
*** Anaconda encountered the following issues during configuration:
GObject introspection must be enabled
Package 'gladeui-2.0', required by 'virtual:world', not found
Package 'gtk+-x11-3.0', required by 'virtual:world', not found
Package 'libxklavier', required by 'virtual:world', not found
Check for gobject-introspection-1.0 >= 1.30 failed

*** Anaconda will not successfully build without these missing dependencies

*** Anaconda encountered the following issues during configuration:
libaudit not found
Unable to find python library
Package 'rpm', required by 'virtual:world', not found
Package 'libarchive', required by 'virtual:world', not found

System: Fedora 27

**Comment by jkonecny12** [comment]
Hello, 

Please use ./scripts/testing/dependency_solver.py to find out missing packages.
