### ISSUE TITLE
Available languages during the installation process

### ISSUE THREAD

**Issue by geekpany** [rhinstaller/anaconda#1826]
![zanata](https://user-images.githubusercontent.com/34344425/52937999-7f49c800-339b-11e9-9197-7a31a4dec1cd.jpg)

Since there are only 3 Chinese L10n languages – `zh_Hans_CN`(简体中文 中国), `zh_Hant_TW`(繁體中文 台灣), `zh_Hant_HK`(繁體中文 中華人民共和國香港特别行政區) – on Zanata, I don’t think it’s a good idea to provide a `zh_Hans_SG`(简体中文 新加坡) option in this menu, which may mislead users to think it’s available while it’s not, obviously.

![anaconda](https://user-images.githubusercontent.com/34344425/52938022-8f61a780-339b-11e9-8822-b7c1eb692299.png)

So I suggest removing `zh_Hans_SG`(简体中文 新加坡) from the menu to make it correspond to Zanata. What would you say?

**Comment by alick** [comment]
I'd like to add that when testing Fedora 30, we found that there is one more Chinese language variant, Mandarin Chinese or 官话 coded as cmn, in the language selection interface. Some as zh_Hans_SG, it's not available on Zanata. Moreover, it's even more confusing since Mandarin refers to the spoken language while Hant or Hans refers to the written language. We believe it should not be listed as an option, although it is a valid language in langtable.

Note that cmn is useful for linguists to differentiate varieties of Chinese, but in everyday life it is practically equal to zh. See also http://www.personal.psu.edu/ejp10/blogs/gotunicode/2009/06/sensible-language-tagging-advi.html

**Comment by jkonecny12** [comment]
Please file this as issue on [Red Hat bugzilla](bugzilla.redhat.com).

**Comment by M4rtinK** [comment]
I think we just show a full language list as returned by the langtable (https://github.com/mike-fabian/langtable) library.

IIRC we currently don't do any matching of the language list to language availability or translation percentage, as the language selection not only translates the UI, but also sets the system language/locale.

I guess we could filter the main list based on translation availability and show the full list in the language support spoke, but that could be confusing to the users why the lists are different.

Alternatively we could maybe show a note for language that have incomplete (<50%) or missing translation when they are selected.

**Comment by geekpany** [comment]
> Please file this as issue on [Red Hat bugzilla](bugzilla.redhat.com).

I've reported it on [RHBZ](https://bugzilla.redhat.com/show_bug.cgi?id=1678787)

**Comment by geekpany** [comment]
> I think we just show a full language list as returned by the langtable (https://github.com/mike-fabian/langtable) library.
> 
> IIRC we currently don't do any matching of the language list to language availability or translation percentage, as the language selection not only translates the UI, but also sets the system language/locale.
> 
> I guess we could filter the main list based on translation availability and show the full list in the language support spoke, but that could be confusing to the users why the lists are different.
> 
> Alternatively we could maybe show a note for language that have incomplete (<50%) or missing translation when they are selected.

Thanks for your reply. About the `cmn` language ID, I've also reported it to the langtable library, see [here](https://github.com/mike-fabian/langtable/issues/8).

**Comment by mike-fabian** [comment]
> I think we just show a full language list as returned by the langtable (https://github.com/mike-fabian/langtable) library.

Really? I don’t think so, langtable has far more languages than anaconda  shows.

It looks like anaconda already does some filtering depending on translation availability.
