### ISSUE TITLE
Update live installer graphics wrt new app icon

### ISSUE THREAD

**Issue by jimmac** [rhinstaller/anaconda#1920]
The live installer will be getting a new application icon. When the user chooses to try the live install rather than installing an info graphic is shown how to launch the installer. 

![installer-graphic](https://user-images.githubusercontent.com/14821/55075297-e2153a00-5092-11e9-92a4-b46a942b1422.png)

This needs to be updated. For the [short term / Fedora 30](https://pagure.io/design/issue/630), I'd update the icon only, but for the future, the [blueprint style](https://gitlab.gnome.org/Teams/Design/app-illustrations/issues/1) might be more appropriate.

**Comment by jkonecny12** [comment]
Please file a bug on bugzilla for this issue. It will be better for linking and process.
