### ISSUE TITLE
Should the product be exposed under core.configuration.anaconda.AnacondaConfiguration.product?

### ISSUE THREAD

**Issue by jcpunk** [rhinstaller/anaconda#1927]
It looks like `core.configuration.anaconda.AnacondaConfiguration` has properties for most of the settings in `data/products.d/`, but it doesn't have one for `Product` or `Base Product`.

I'm not sure how this would work exactly, but it seemed odd to me....

**Comment by poncovka** [comment]
We don't have a use case for it at this point. The module `pyanaconda.product` provides all information about the current product, so we use this module. The sections `Product` and `Base Product` only describe the product configuration file, not the product.

**Comment by jcpunk** [comment]
Ok, just making sure it wasn't an oversight.
