### ISSUE TITLE
Install using anaconda causes kernel panic.

### ISSUE THREAD

**Issue by avairavan** [rhinstaller/anaconda#1938]
We use the anaconda 21.48.22.147-1to install our software in an embedded device. Our stress tests do this installation in a continuous loop in which the installation is successful almost 99% of the time but sometimes the installation fails and leads to kernel panic.

The anaconda based installation fails while installing the bootloader. The anaconda logs are redirected to a remote server which indicates the installation failed while manipulating the boot order using efibootmgr

`Apr  2 23:54:05 localhost blivet:         DeviceTree.getDevicesByInstance returned []
Apr  2 23:54:05 localhost program: Running... xfs_freeze -f /boot
Apr  2 23:54:05 localhost program: Return code: 0
Apr  2 23:54:05 localhost program: Running... xfs_freeze -u /boot
Apr  2 23:54:05 localhost program: Running... efibootmgr

<Nothing after this>`

At this time, the system got rebooted (not sure why). After this reboot, the kernel panic as shown below.

![QA119-Node1PanicCannotMountRoot](https://user-images.githubusercontent.com/16446281/55663458-089e4800-57ec-11e9-89ce-9b5136b801ae.PNG)

This kernel panic is because the path to initrd image is not specified in the grub (i.e) the following line is missing in the grub entry.

`initrdefi /initramfs-3.10.0-862.14.4.el7.x86_64.img`

A couple of questions:

1. What could have caused the system to reboot in the middle of bootloader installation?
2. Why the grub entry is messed up and missing initdefi?

Appreciate any help

**Comment by jkonecny12** [comment]
Hello.
Please file this bug on [Red Hat bugzilla](bugzilla.redhat.com) so we can properly switch the components and add `nokill` to the kernel parameters to avoid rebooting of the system. Then you should be able to collect logs.

To avoid blocking the stress tests by manually doing reboots you can add reboot to the %post section of kickstart file so the system will reboot under "normal' circumstances.

Closing the Issue now, we will continue in the bugzilla, please.

**Comment by avairavan** [comment]
Thanks. Will move it to Red Hat bugzilla forum
