### ISSUE TITLE
installation media implicitly included as an installation destination

### ISSUE THREAD

**Issue by MSK61** [rhinstaller/anaconda#1958]
I've created a live USB installation media for fedora 30 on a partition on an external USB hard drive. I booted my PC to the USB hard drive and got into a live fedora graphical environment. I then started the installer to install fedora to an internal drive(different from the external USB drive I booted from).

Now I get to selecting the "Installation Destination" in Anaconda installer. Of course the external USB drive isn't listed among the "Local Standard Disks" as expected. I then select an internal disk to install fedora to, as seen in this screenshot.
![](https://forums.fedoraforum.org/attachment.php?attachmentid=30275&d=1556840179)

After I free some space on the selected destination drive and get back to the "INSTALLATION SUMMARY" screen, I have a red "Error checking storage configuration" error message under the "Installation Destination" icon, as seen here.
![](https://forums.fedoraforum.org/attachment.php?attachmentid=30276&d=1556840394)

When I enter the "INSTALLATION DESTINATION" screen again, I have the same error message at the very bottom of the screen.
![](https://forums.fedoraforum.org/attachment.php?attachmentid=30277&d=1556840522)

When I click the "Click for details." link, I see the following dialog.
![](https://forums.fedoraforum.org/attachment.php?attachmentid=30278&d=1556840728)

/dev/sdb1 is the partition on my external USB drive that's holding the live installation image I've booted from. It's normal to be mounted since I'm running the installer from within the live media. It seems the installer sees this external drive as a destination for the installation(although I've obviously not selected it for such a purpose and it wasn't even listed in the local disks screen above). Of course trying to unmount the partition goes in vain as it's still being used(and thus failure of the umount command makes sense).

It's noteworthy that I have always used that exact method of installation for many previous releases of fedora without any problem. May it be because fedora 30 installer is using a more recent version of anaconda that's suffering from this problem?

**Comment by MSK61** [comment]
Just for reference, I've first expressed the problem on [fedoraforum](https://forums.fedoraforum.org/showthread.php?321290-Can-t-fresh-install-fedora-30-from-external-USB-hard-drive).

**Comment by jkonecny12** [comment]
Please file this as a bug to the bugzilla.redhat.com and add logs from the /tmp/*.log.

You can just make a brief description with the link here but it will me much easier to work with the issue on bugzilla instead of here.

Thanks and sorry for any inconvenience.

**Comment by MSK61** [comment]
Almost a week ago I opened a corresponding bug on bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1706335. All details and relevant logs have already been added there as well.

**Comment by jkonecny12** [comment]
Thank you :+1:
