### ISSUE TITLE
Missing local variable check

### ISSUE THREAD

**Issue by usta** [rhinstaller/anaconda#34]
The "warning" (local variable) is not defined in whole conditions thus it causes "Not defined" error in
anaconda/pyanaconda/ui/gui/hubs/__init__.py
We can solve this with 1 - define a warning=_(" ") or 2- we can check if is it defined or not before using it.

**Comment by dashea** [comment]
Fixed in https://github.com/rhinstaller/anaconda/commit/97a004c5d0e38240ffbbfc6d459cac8d1da70cea
