### ISSUE TITLE
tests/README.rst missing from tarball (src.rpm)

### ISSUE THREAD

**Issue by atodorov** [rhinstaller/anaconda#391]
anaconda-24.3-1.fc24.src.rpm, extracted the tarball inside and tests/README.rst is missing. Now I have to resort back to the git repo to figure out how to run the tests.

Let me know what creates the tarball and I'll submit a patch if you're busy.

**Comment by atodorov** [comment]
scripts/makebumpver is also missing so I can't execute `make ci` from inside the tarball sources.

**Comment by vpodzime** [comment]
These need to be added in the particular ``Makefile.am`` files. Probably as ``EXTRA_DIST``.

**Comment by vpodzime** [comment]
``scripts/makebumpver`` should probably be ``dist_noinst_SCRIPTS``

**Comment by atodorov** [comment]
vpodzime:  `dist_noinst_SCRIPTS` in the main Makefile.am ? Can you comment on #393. Thanks.
