### ISSUE TITLE
Multiple calls to make check overwrites test-suite.log

### ISSUE THREAD

**Issue by atodorov** [rhinstaller/anaconda#452]
`make ci` calls `make check` several times which overwrites test-suite.log every time. In the end we've lost the nice summary of how many tests were executed and what their status was. 

I've tried adding a pid suffix to TEST_SUITE_LOG but that doesn't work b/c of the way make calls its internal targets. For example this will not work if you do `make test`

```
PID ?= $(shell pidof -s make)
LOG = test.log.$(shell pidof make)

test:
	echo $(LOG)
	$(MAKE) $(LOG)

$(LOG):
	echo $(LOG)
```

Another issue is that everything needs to pass if we're to collect output of pid stamped test-suite.log at the end. Otherwise make will simply abort after the failure. 

Any ideas how this can be fixed ?

**Comment by dashea** [comment]
make ci runs the individual make checks in series, so shouldn't it be possible to just set TEST_SUITE_LOG for the other calls? Maybe not using a PID, but just a different file name, like

```
diff --git a/Makefile.am b/Makefile.am
index 4e95e12..4aafe36 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -177,12 +177,13 @@ ci: rc-release
        $(MAKE) -C utils/dd
        $(MAKE) TMPDIR=/var/tmp COVERAGE_PROCESS_START=$(abs_builddir)/.coveragerc check
        @sudo $(MAKE) TMPDIR=/var/tmp COVERAGE_PROCESS_START=$(abs_builddir)/.coveragerc \
-               TESTS=nosetests_root.sh check
+               TESTS=nosetests_root.sh TEST_SUITE_LOG=root-test-suite.log check
        @tail -n 1 tests/gettext_tests/*.log > tests/gettext_tests/gettext_tests.log
        @mkdir -p repo
        @mv *rpm repo
        @createrepo -p repo
-       @sudo $(MAKE) TMPDIR=/var/tmp TESTS=install/run_install_test.sh TEST_ANACONDA_REPO=file://$(abs_builddir)/repo/ COVERAGE_PROCESS_START=$(abs_builddir)/.coveragerc check
+       @sudo $(MAKE) TMPDIR=/var/tmp TESTS=install/run_install_test.sh TEST_ANACONDA_REPO=file://$(abs_builddir)/repo/ COVERAGE_PROCESS_START=$(abs_builddir)/.coveragerc \
+               TEST_SUITE_LOG=install-test-suite.log check
        @rm -f $(USER_SITE_PACKAGES)/usercustomize.py
        @sudo rm -f $(ROOT_SITE_PACKAGES)/usercustomize.py
        $(MAKE) coverage-report
```

**Comment by dashea** [comment]
If you do want a PID in there adding $$ (or I guess \$\$ after escaping for make) in the environment at the point of the individual commands should work
