### ISSUE TITLE
dracut: fails to fetch kickstart reliably on v6-only networks

### ISSUE THREAD

**Issue by bwann** [rhinstaller/anaconda#464]
When kickstarting a CentOS 7 host on an IPv6-only network, there's a race condition between bringing up the network, learning the v6 gateway via RA, and fetching the kickstart which often causes it to fail and eventually drop to a dracut emergency prompt.

Snippet of failure: https://gist.github.com/bwann/7bc1c4217807b01087ff

Right before the failure it shows the Ethernet link state changing up/down/up. Based on the "network is unreachable" errors, I highly suspect what's happening is that the link is considered online and dracut continues to try to fetch kickstart+stage2 images before the host has been able to do a v6 router solicitation and learn its default gateway from a router advertisement.

It seems to be a very short race, for if I turn on dracut debug with rd.debug, it slows down the process *just* enough that this never happens. As a hacky workaround, I've inserted a file (/usr/lib/dracut/hooks/initqueue/online/10-fb-network-sleep-fix.sh) in the initramfs that does nothing but sleep 2 seconds before dracut tries to download the kickstart and stage2, and it reliably fixes the problem.

Examples network config on cmd line: "ip=[2401:db00:1020:da:face:0:1:0]:::64:::none noipv4"

If I specify a gateway on the kernel command line, this also fixes the problem, but this is not a solution as we require learning our v6 default gateway from RAs; we can not pre-configure them.

It looks like the dracut scripts need to do a better job of detecting a usable link. I'm also wondering why there isn't a retry mechanism here?  I've looked at the new code in the rhel7-branch for RHEL7.2 and don't see any fixes here.

There's also a very similar problem within Anaconda itself which I'll open a separate issue for. NetworkManager brings up the network and anaconda tries to configure repos and fetch treeinfo files, but curl fails due to the same "network is unreachable" line, and marks all repos as unusable.

--bwann

**Comment by bcl** [comment]
Please open bugs with the relevant components at https://bugzilla.redhat.com, it will help debugging if you attach the logs from /tmp/*log to the bug, as well as the output when running with rd.debug.
