### ISSUE TITLE
Race condition between NetworkManager and anaconda in v6-only installs causes packages selection to fail

### ISSUE THREAD

**Issue by bwann** [rhinstaller/anaconda#466]
Similar to issue #464 that I opened yesterday for dracut, there's a second race condition in kickstarting a CentOS 7 host on a v6-only network. Here NetworkManager is started (roughly) simultaneously as Anaconda is via systemd, but NetworkManager doesn't transition the NIC to CONNECTED_GLOBAL until 273 miliseconds (in this example) after Anaconda tries to retrieve package/treeinfo information. URLGrabber/curl fails on a "Network is unreachable" error, which I believe is because the host doesn't have a v6 gateway from a router solicitation/advertisement yet.

I can reproduce this pretty reliably on my hosts. I'm using stock CentOS 7.1, which has anaconda 19.31.123-1 and dracut 033-240.

This failure to fetch repo information results in Anaconda halting with software selection errors on console:

```
3) [!] Software selection (Installation source not set up)
4) [!] Installation source (Error setting up software source)
```

Example syslog+packaging.log showing the race:
```
01:13:20,686 DEBUG packaging: getting release version from tree at http://[2401:db00:11:df:face:b00c:0:134]/yum/centos/7.x/os/x86_64 (7)
01:13:20,686 DEBUG packaging: retrieving treeinfo from http://[2401:db00:11:df:face:b00c:0:134]/yum/centos/7.x/os/x86_64 (proxy:  ; sslverify: True)
01:13:20,687 INFO packaging: Error downloading treeinfo: [Errno 14] curl#7 - "Failed to connect to 2401:db00:11:df:face:b00c:0:134: Network is unreachable"

01:13:20,959 INFO NetworkManager: <info>  NetworkManager state is now CONNECTED_GLOBAL
01:13:20,960 INFO NetworkManager: <info>  Policy set 'System eth0' (eth0) as default for IPv6 routing and DNS.
```
Logs from NetworkManager and packaging.log:  https://gist.github.com/bwann/396ea39750264ebb56a6

My hack to get around this for now has been to introduce another sleep via systemd service entry within stage2 (/usr/lib/systemd/system/fb-fix-ipv6-gw-wait.service) before Anaconda starts:

```
[Unit]
Description=FB pre-anaconda two-second IPv6 hack
Before=anaconda.service

[Service]
Type=oneshot
ExecStart=/bin/sleep 2
```

--bwann

**Comment by bcl** [comment]
Thanks for the report, but bugs like this are better handled via https://bugzilla.redhat.com, please open a bug there against anaconda.
