### ISSUE TITLE
anaconda should not crash when an invalid disk configuration is found

### ISSUE THREAD

**Issue by lantw44** [rhinstaller/anaconda#473]
This problem was reported to blivet: https://github.com/rhinstaller/blivet/issues/288

As anaconda is an OS installer, I think it should be able to handle or ignore invalid settings instead of crashing, showing traceback or asking users to debug. I hope it can ask blivet to ignore invalid disks, so Fedora can still be installed on other valid disks even if invalid disks exist.

**Comment by dashea** [comment]
https://github.com/rhinstaller/anaconda/blob/master/pyanaconda/errors.py#L123

If you are actually encountering a crash please create a bug at http://bugzilla.redhat.com/ and include the traceback file written to /tmp/anaconda-tb-*

**Comment by lantw44** [comment]
Can it be modified to ignore non-working disks instead of showing errors?
