### ISSUE TITLE
Should DNF payload use it's substitutions?

### ISSUE THREAD

**Issue by jcpunk** [rhinstaller/anaconda#493]
https://github.com/rhinstaller/anaconda/blob/master/pyanaconda/packaging/dnfpayload.py#L237 is a "_replace_vars" function.

DNF provides dnf.conf.substitutions which will pull in any DNF supported vars automatically.

This would allow for substitutions other than $basearch and $releasever while also moving the maintenance of expected vars out of anaconda.

**Comment by bcl** [comment]
Sounds like a good idea.
