### ISSUE TITLE
Conversion to py3 print statement caused change in behavior for list-harddrives

### ISSUE THREAD

**Issue by gregswift** [rhinstaller/anaconda#5]
When it happened: 82476e8a2a2d901082f2c5d591a5f4ff2a7cbd87

I just ran into an issue where the output of anaconda's list-harddrives seem to have changed.  I've googled and checked the fedora wiki and haven't found any mention of this.

An example from before (and what all the search reslt i have on it expect):
```
# list-harddrives
sda 8394.0
```

The output on Fedora 21:
```
# list-harddrives
('sda', 8394.0)
```

This is painful because lots of people have automation around parsing the output during kickstarts.

The common handling you will see when researching this is something akin to this:
```
set $(list-harddrives)
disk=$1
```

Before echoing $disk would return
```
sda
```

Now echo $disk gives you
```
('sda',﻿
```

**Comment by mulkieran** [comment]
Thanks for the report.

The problem w/ the offending patch, which changes
print dev, size
to
print(dev, size)
is that it results in no change for Python 3, but gets you the parens in Python 2.
A format string should yield the fix.

Occurances of this change pattern can be found in:
data/command-stubs/list-harddrives-stub
pyanaconda/ui/tui/tools/run-text-spoke.py

and as far as I can tell, that's it.

**Comment by mulkieran** [comment]
Patch posted.

**Comment by mulkieran** [comment]
Pushed.
