### ISSUE TITLE
Copy kickstart files form /tmp/ks.cfg to /mnt/sysimage/root/ks.cfg on completion

### ISSUE THREAD

**Issue by nkadel** [rhinstaller/anaconda#642]
[ Our friends over on pykickstart sent me over here with this. ]

Many people who use kickstart files find the discrepancies between the actual kickstart file used for bulk deployment, and the published "/root/anaconda-ks.cfg", to be confusing and even invalidating. The "anaconda-ks.cfg", for example, does not reliably publish copies of multiple '%pre' or '%post' operations. Also, the re-arrangement of a valid kickstart file into the anaconda-ks.cfg default format, which does not match the format produced by the various "system-config-kickstart" tools makes the direct comparision and source control of kickstart files additionally difficult.

So please: if a kickstart file is used, it is typically downloaded to /tmp/ks.cfg in the load environment. Simply execute a "%post --nochroot" like step and copy "/tmp/ks.cfg" to "/mnt/sysimage/root/ks.cfg"

**Comment by bcl** [comment]
This was added in anaconda-24.7-1 and will also be present in RHEL 7.3, it will be copied to /root/original-ks.cfg

**Comment by nkadel-skyhook** [comment]
Any chance of backporting it to RHEL 6.8? There are a lot of servers still running that.
