### ISSUE TITLE
f21 server: generated kickstart invalid network hostname line

### ISSUE THREAD

**Issue by FlorianLudwig** [rhinstaller/anaconda#72]
generated ks:
```
network  --hostname=foobar
```

booterror:
```
parse-kickstart ERROR: `network  --hostname=foobar`: missing --device
```

**Comment by vpodzime** [comment]
@rvykydal, can you please have a look at this?

**Comment by dashea** [comment]
It's not invalid, it's just that parse-kickstart shouldn't be complaining. Network.dracut_args should probably be changed to handle network lines with just a hostname. I think there's a bug open about the same issue somewhere.

**Comment by rvykydal** [comment]
I believe this has been fixed on master with
https://github.com/rhinstaller/anaconda/commit/dde9b9335155c37c42abf243d3976a54e5d40ad5

**Comment by dashea** [comment]
Closing since this is fixed by the referenced commit
