### ISSUE TITLE
f21 server kickstart: "Failed to save storage configuration" with no error

### ISSUE THREAD

**Issue by FlorianLudwig** [rhinstaller/anaconda#73]
Using fedora 21 server with a kickstart file the anaconda gui claims "failed to save storage configuration" without any further information on what went wrong.

Log and kickstart file: https://gist.github.com/FlorianLudwig/2983b6141ae213deafe8

**Comment by FlorianLudwig** [comment]
Well, there is a warning about "swap" being declared twice - which seems to be another bug (https://github.com/rhinstaller/pykickstart/issues/7)

**Comment by dashea** [comment]
If this is still an issue, please open a bug at http://bugzilla.redhat.com and attach all of the logs from /tmp.
