### ISSUE TITLE
RFE: Please improve anaconda visual accessibility

### ISSUE THREAD

**Issue by adamemerson** [rhinstaller/anaconda#745]
I was trying to install Fedora 24 and the text and mouse pointer were far too small to be comfortably readable for me. There did not seem to be a way to increase the font and mouse cursor size.

I attempted booting with the `lowres` option, but found fairly soon (on the dialogue to configure the wireless network) that much of the user interface disappeared off the right side of the screen and there seemed no way to scroll over to it.

I then tried turning off modesetting entirely and using the text mode installer, but the text mode installer seems to have many pieces missing and is not wonderful.

Is there a chance you could make the font/cursor size a parameter that could be specified on the kernel command line or some other way?

Thank you.

**Comment by jkonecny12** [comment]
Hi, thanks for the report. Could you please [file a bug report in Red Hat Bugzilla](https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&version=24&component=anaconda) and add some extra information like screen resolution, screenshots, etc.? Thanks!
