### ISSUE TITLE
EXTLINUX isn't installed to MBR

### ISSUE THREAD

**Issue by SocDemScum** [rhinstaller/anaconda#754]
EXTLINUX is configured and installed to the filesystem, but is not installed to the MBR so systems using EXTLINUX cannot boot.

EXTLINUX can be installed to the MBR of the boot device by running:
`dd if=/usr/share/syslinux/mbr.bin of=/dev/device`

Unfortunately I don't know enough about how Anaconda and Git works to be able to submit patches for this issue

**Comment by bcl** [comment]
Please file a bug report at https://bugzilla.redhat.com with the logs from /tmp/*log attached as individual text/plain attachments.

**Comment by jkonecny12** [comment]
Hello, if you have the patch somewhere you can just create Pull Request to the ``master`` branch or ``rhel7-branch`` or you can just attach a patch file to the bug in bugzilla. In any case please report this to the bugzilla.

We are not using GitHub issues so I'm closing this.
Thank you for your report!
