### ISSUE TITLE
Need dnf distro-sync in Makefile install-buildrequires?

### ISSUE THREAD

**Issue by bwann** [rhinstaller/anaconda#757]
After 26.1 was released, I tried to re-build things from source inside a fresh Rawhide mock chroot and didn't get past the first `make -f Makefile.am install-buildrequires` step. DNF claimed it needed glib2 = 2.49.5-1.fc26 but couldn't be installed.

Full error output:
https://gist.github.com/bwann/801fa0702c36032c5c3349cbeb172ec8

After doing a `dnf distro-sync` it was able to fix the glib2 dependency and make continued on. Do we need to include this step in the makefile, it was this a side effect of something else?

fwiw this is what our script is running in the chroot:
```
INFO: Running in chroot:
  cd /root
  git clone  https://github.com/rhinstaller/anaconda.git
  dnf distro-sync
  cd anaconda
  yes | make -f Makefile.am install-buildrequires
  ./autogen.sh
  ./configure
  make scratch
```

**Comment by M4rtinK** [comment]
That seems to be just some transient Rawhide packaging breakage -  I've tried to build Anaconda in F24 mock, using the same commands, and the issue does not happen.

So I don't think changes in the Anaconda Makefile are needed.

**Comment by bwann** [comment]
Yeah, seems to have been transient. I took the command out of my script and it's building against Rawhide again.
