### ISSUE TITLE
SettingsNotFoundError('eth1',) with FC26 Rawhide + dual NIC host

### ISSUE THREAD

**Issue by bwann** [rhinstaller/anaconda#767]
When running Anaconda (25.20-1 or 26.1-1) on Fedora Rawhide from this week on a host with dual NICs, I get a traceback for `pyanaconda.nm.SettingsNotFoundError: SettingsNotFoundError('eth1',)` on the unconfigured NIC. Kickstart only contains a network line for `eth0`.

This was working last week on Rawhide, and looks to be related to the version of NetworkManager included. Previously 1.4.0-5.05 would show a `System eth0` and `eth1`:

```
nmcli tool, version 1.4.0-0.5.git20160621.072358da.fc26

[anaconda root@sparefullhaystack1419 tmp]# nmcli c show
NAME         UUID                                  TYPE            DEVICE
System eth0  0d0d5f81-4077-464a-bc87-b20a06ece717  802-3-ethernet  eth0
eth1         85666543-e6e5-3923-a070-2ca95298b825  802-3-ethernet  --
```

Now with 1.4.0-2 on the exact same hardware it's showing a `System eth0` and `Wired connection 1`:

```
nmcli tool, version 1.4.0-2.fc26

[anaconda root@localhost tmp]# nmcli c show
NAME                UUID                                  TYPE            DEVICE
System eth0         a9b26902-8dc6-455a-a397-ecedd9bec00c  802-3-ethernet  eth0
Wired connection 1  2261fa86-df89-3b11-8640-16e86580e0e7  802-3-ethernet  --
```

I suspect the "wired connection" vs "eth1" is confusing Anaconda. I'm not sure if Anaconda needs to be fixed to accommodate or if this is NetworkManager brokenness.

Traceback, ifcfg.log: https://gist.github.com/bwann/a146456ed99450546f1948b06ba86db7

**Comment by bwann** [comment]
ah hah! Looks like this is fixed with https://github.com/rhinstaller/anaconda/pull/752

**Comment by rvykydal** [comment]
For the reference, PR for master: #769
