### ISSUE TITLE
Improvable message text 

### ISSUE THREAD

**Issue by jaaf** [rhinstaller/anaconda#787]
While proofreading the French translation of anaconda, I found this sentence a bit unclear : 

> If you would like to make your system the root environment, run the command:

Is the term "root environment" sufficiently well known  and clear to be used in this context?

I suggest:

> If you would like make the root of your system the root of the active system, run the command:

**Comment by jkonecny12** [comment]
Thank you for noticing this. I did the PR with your proposed change.

**Comment by jkonecny12** [comment]
Closed by 7336ace50a45d7abefcedd19355258794dc6952e
