### ISSUE TITLE
installclass vs autopart

### ISSUE THREAD

**Issue by cgwalters** [rhinstaller/anaconda#800]
I'm seeing an issue that replicates with Fedora Server as well as some Atomic Workstation bits I'm working on (but _not_ with F24 Atomic Host for some reason) where all of these projects override the default partitioning in their product images, but it _doesn't_ apply if one interactively clicks "Create partitions for me".

It does work though when accepting the default autoparts without going to that screen at all.

I think there's an ordering issue here - we need to run through the product images partitioning setup early on in bootup to change the blivet defaults, rather than waiting for kickstart processing.

**Comment by cgwalters** [comment]
One thing that makes this a bit more urgent for me is that for Atomic Host|Workstation systems, it needs to be `/var/home/` by default.

**Comment by dwlehman** [comment]
You're exactly right. A "snapshot" is made of the `Blivet` instance in the storage spoke before `pyanaconda.kickstart.doKickstartStorage` runs. `setDefaultPartitioning` should definitely be run earlier than that.

**Comment by dwlehman** [comment]
Untested patch: dwlehman/anaconda@846ad15e

If you test this and it works, let me know what version of Fedora this is targeting and I'll open a pull request.

**Comment by cgwalters** [comment]
Any movement on this?  It's going to be a lot more important when more products try to change partitioning.

**Comment by poncovka** [comment]
Hi, I was able to reproduce and fix the bug. With the fix, it looks that the default partitioning works always the same way now. Could you also test it and confirm, that it solves the issue, please? The pull request is here: [https://github.com/rhinstaller/anaconda/pull/905](https://github.com/rhinstaller/anaconda/pull/905).

**Comment by poncovka** [comment]
The pull request was merged.
