### ISSUE TITLE
Nothing happens when clicking 'Open Terminal' on anaconda-navigator environment

### ISSUE THREAD

**Issue by brylie** [rhinstaller/anaconda#821]
In Anaconda Navigator, clicking 'Open Terminal' (in the green arrow popup menu) produces no result.

# Goal
I am trying to launch Orange3, by creating a new environment with the older Qt 4.x packages.

# Environment
- OS: Ubuntu 16.04
- Desktop: KDE Plasma 5.8.0

**Comment by vpodzime** [comment]
Are you sure, you are targeting the right Anaconda here, @brylie ? This repo is for the Anaconda OS Installer used by Fedora, RHEL, CentOS and other Linux distributions.

**Comment by brylie** [comment]
OK, what repo should I move this issue to?

**Comment by brylie** [comment]
I moved the issue here: https://github.com/ContinuumIO/anaconda-issues/issues/1139

**Comment by brylie** [comment]
Apologies for the confusion.
