### ISSUE TITLE
RFE: don't reboot when %post --erroronfail in cmdline mode 

### ISSUE THREAD

**Issue by dustymabe** [rhinstaller/anaconda#931]
so I realize in cmdline mode we should never expect the user input, but for `--erroronfail` it would be nice if it actually does stop the installation because otherwise, if the user doesn't go back and look at the logs of the install, they never know the install failed. This is what it does now:
```
.
Running post-installation scripts

The installation was stopped due to incomplete spokes detected while running in non-interactive cmdline mode. Since there cannot be any questions in cmdline mode, edit your kickstart file and retry installation.
The exact error message is:

Non interactive installation failed: .

The installer will now terminate.
```

The most prime example of this is in Fedora. There are many issues in our post scripts that we weren't noticing because we have --erroronfail set, but the installation doesn't "stop" but continues and does the reboot. This means imagefactory doesn't detect that the install failed; imagefactory uses a somewhat crude but somewhat effective method of detecting if the install failed by measuring disk activity and timing out. 

So in [this](https://pagure.io/fedora-kickstarts/blob/f85bbb10ee3d4429684a6e855e08f6ad33621897/f/fedora-docker-base.ks) kickstart we have [cmdline set](https://pagure.io/fedora-kickstarts/blob/f85bbb10ee3d4429684a6e855e08f6ad33621897/f/fedora-docker-base.ks#_18) and we also have a [part of the %post](https://pagure.io/fedora-kickstarts/blob/f85bbb10ee3d4429684a6e855e08f6ad33621897/f/fedora-docker-base.ks#_79) that has been failing for a while.

The simple workaround for this is to use `text` vs `cmdline` but I think it would be better to just do what [--erroronfail](http://pykickstart.readthedocs.io/en/latest/kickstart-docs.html#chapter-5-post-installation-script) claims it will do instead.

**Comment by jkonecny12** [comment]
Good point. Thank you for pointing us to this behavior.

**Comment by rvykydal** [comment]
https://github.com/rhinstaller/anaconda/pull/1105

**Comment by rvykydal** [comment]
Closing as https://github.com/rhinstaller/anaconda/pull/1105 has been merged.
