### ISSUE TITLE
 RFE: extend autopart with options to disable separate boot/swap partitions

### ISSUE THREAD

**Issue by nullr0ute** [rhinstaller/anaconda#991]
new because of this: https://github.com/rhinstaller/blivet/issues/551

from https://bugzilla.redhat.com/show_bug.cgi?id=1220866

The Fedora cloud images use the following kickstart option for disk partitioning because a boot/swap partition isn't needed or useful.

zerombr
clearpart --all
part / --size 3000 --fstype ext4

The issue is that some virtual HW needs some other options like /boot/efi for virt platforms that use uEFI boot or PrEP for POWER platforms which are handled well with autopart in an architecture independent manner.

It would be useful to have --noboot and --noswap options for the autopart option as a result. That way something like the following could be used for all architectures:

autopart --nolvm --noboot --noswap

It's also not unusual these days for installs not to want to use swap space so it's useful in general

**Comment by poncovka** [comment]
Hello, rawhide is not our biggest priority right now, but I would like to implement `--noboot` and `--noswap` options together with `--nohome `as soon as I will find some time for that.

**Comment by poncovka** [comment]
The pull request https://github.com/rhinstaller/anaconda/pull/1021 was merged. Closing the issue.
